# Generated by Django 4.1.3 on 2022-12-25 16:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_seller_create_date_user_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='create_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата створення'),
        ),
    ]
